version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:beta
    container_name: verdaccio-3-docker-plugin-external
    ports:
      - "4873:4873"
    volumes:
        - "./storage:/verdaccio/storage"
        - "./conf:/verdaccio/conf"
        - "./plugins:/verdaccio/plugins"